org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kapt.use.k2=false
org.gradle.java.home=C:/Program Files/Zulu/zulu-17
PURR_VERSION_NAME=0.2.5
PURR_VERSION_CODE=16
PURR_PRODUCTION_BASE_URL=https://api.purr.fxs.life/
